//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosWeb.ClienteConsola.ServiceClienteASMX {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfCliente", Namespace="http://tempuri.org/", ItemName="cliente")]
    [System.SerializableAttribute()]
    public class ArrayOfCliente : System.Collections.Generic.List<ServiciosWeb.ClienteConsola.ServiceClienteASMX.cliente> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="cliente", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdTrabajadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        private System.Nullable<int> EdadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        private System.Nullable<System.DateTime> FechaNacField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdTrabajador {
            get {
                return this.IdTrabajadorField;
            }
            set {
                if ((this.IdTrabajadorField.Equals(value) != true)) {
                    this.IdTrabajadorField = value;
                    this.RaisePropertyChanged("IdTrabajador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> Edad {
            get {
                return this.EdadField;
            }
            set {
                if ((this.EdadField.Equals(value) != true)) {
                    this.EdadField = value;
                    this.RaisePropertyChanged("Edad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<System.DateTime> FechaNac {
            get {
                return this.FechaNacField;
            }
            set {
                if ((this.FechaNacField.Equals(value) != true)) {
                    this.FechaNacField = value;
                    this.RaisePropertyChanged("FechaNac");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceClienteASMX.ServicioClienteSoap")]
    public interface ServicioClienteSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerClienteResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCliente", ReplyAction="*")]
        ServiciosWeb.ClienteConsola.ServiceClienteASMX.ObtenerClienteResponse ObtenerCliente(ServiciosWeb.ClienteConsola.ServiceClienteASMX.ObtenerClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiciosWeb.ClienteConsola.ServiceClienteASMX.ObtenerClienteResponse> ObtenerClienteAsync(ServiciosWeb.ClienteConsola.ServiceClienteASMX.ObtenerClienteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCliente", Namespace="http://tempuri.org/", Order=0)]
        public ServiciosWeb.ClienteConsola.ServiceClienteASMX.ObtenerClienteRequestBody Body;
        
        public ObtenerClienteRequest() {
        }
        
        public ObtenerClienteRequest(ServiciosWeb.ClienteConsola.ServiceClienteASMX.ObtenerClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerClienteRequestBody {
        
        public ObtenerClienteRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiciosWeb.ClienteConsola.ServiceClienteASMX.ObtenerClienteResponseBody Body;
        
        public ObtenerClienteResponse() {
        }
        
        public ObtenerClienteResponse(ServiciosWeb.ClienteConsola.ServiceClienteASMX.ObtenerClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiciosWeb.ClienteConsola.ServiceClienteASMX.ArrayOfCliente ObtenerClienteResult;
        
        public ObtenerClienteResponseBody() {
        }
        
        public ObtenerClienteResponseBody(ServiciosWeb.ClienteConsola.ServiceClienteASMX.ArrayOfCliente ObtenerClienteResult) {
            this.ObtenerClienteResult = ObtenerClienteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioClienteSoapChannel : ServiciosWeb.ClienteConsola.ServiceClienteASMX.ServicioClienteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClienteSoapClient : System.ServiceModel.ClientBase<ServiciosWeb.ClienteConsola.ServiceClienteASMX.ServicioClienteSoap>, ServiciosWeb.ClienteConsola.ServiceClienteASMX.ServicioClienteSoap {
        
        public ServicioClienteSoapClient() {
        }
        
        public ServicioClienteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClienteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClienteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClienteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiciosWeb.ClienteConsola.ServiceClienteASMX.ObtenerClienteResponse ServiciosWeb.ClienteConsola.ServiceClienteASMX.ServicioClienteSoap.ObtenerCliente(ServiciosWeb.ClienteConsola.ServiceClienteASMX.ObtenerClienteRequest request) {
            return base.Channel.ObtenerCliente(request);
        }
        
        public ServiciosWeb.ClienteConsola.ServiceClienteASMX.ArrayOfCliente ObtenerCliente() {
            ServiciosWeb.ClienteConsola.ServiceClienteASMX.ObtenerClienteRequest inValue = new ServiciosWeb.ClienteConsola.ServiceClienteASMX.ObtenerClienteRequest();
            inValue.Body = new ServiciosWeb.ClienteConsola.ServiceClienteASMX.ObtenerClienteRequestBody();
            ServiciosWeb.ClienteConsola.ServiceClienteASMX.ObtenerClienteResponse retVal = ((ServiciosWeb.ClienteConsola.ServiceClienteASMX.ServicioClienteSoap)(this)).ObtenerCliente(inValue);
            return retVal.Body.ObtenerClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiciosWeb.ClienteConsola.ServiceClienteASMX.ObtenerClienteResponse> ServiciosWeb.ClienteConsola.ServiceClienteASMX.ServicioClienteSoap.ObtenerClienteAsync(ServiciosWeb.ClienteConsola.ServiceClienteASMX.ObtenerClienteRequest request) {
            return base.Channel.ObtenerClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiciosWeb.ClienteConsola.ServiceClienteASMX.ObtenerClienteResponse> ObtenerClienteAsync() {
            ServiciosWeb.ClienteConsola.ServiceClienteASMX.ObtenerClienteRequest inValue = new ServiciosWeb.ClienteConsola.ServiceClienteASMX.ObtenerClienteRequest();
            inValue.Body = new ServiciosWeb.ClienteConsola.ServiceClienteASMX.ObtenerClienteRequestBody();
            return ((ServiciosWeb.ClienteConsola.ServiceClienteASMX.ServicioClienteSoap)(this)).ObtenerClienteAsync(inValue);
        }
    }
}
